### ISSUE TITLE
Zod <-> JSON <-> Database possible here?

### ISSUE THREAD

**Issue by purplecones** [StefanTerdell/zod-to-json-schema#17]
Hi I am researching tools for a survey-like application I will be building that requires user generated forms. I was wondering if something like this would be possible with this package where I would save the Zod equivalent JSON schema to the DB and later convert it back to Zod with React Hook Form to generate the form. Any thoughts would be helpful. Thank you!

**Comment by StefanTerdell** [comment]
Since Zod is inherently unserialisable considering parts of the schema can only be described with code (such as transforms, effects etc.) I would argue against keeping Zod schemas as your one source of truth if you are going to be sharing models with a database. Maybe there are some projects in the ecosystem to adress this but I haven't used or seen any myself.

That said I do have a [json-schema-to-zod](https://github.com/StefanTerdell/json-schema-to-zod) package. It produces a JS string but should be safe to eval(). So that's one way I guess.

If I were you I'd migrate to json schemas and then for types either use something like [json-schema-to-ts](https://www.npmjs.com/package/json-schema-to-ts) or this package to create Zod schemas for client/server runtime/DX. Of course Zod bundles typings with validation so it's easy to work with, but the ecosystem for json schema is a lot larger for things like form generation and database integration so either way is probably fine.

GL & HF
