### ISSUE TITLE
How can I specify the format?

### ISSUE THREAD

**Issue by thelinuxlich** [StefanTerdell/zod-to-json-schema#95]
I want to specify a file upload format like described in https://swagger.io/docs/specification/describing-request-body/file-upload/ which needs to be `binary`. Is it possible to do this?

**Comment by StefanTerdell** [comment]
How would you describe that in a Zod schema?

**Comment by thelinuxlich** [comment]
I'd convert these to binary:

```ts
z.instanceof(File)
z.instanceof(Buffer)
z.instanceof(Blob)
```

**Comment by StefanTerdell** [comment]
There's no way to serialize an instanceof check unfortunately, and you're not describing the serialized data with that schema anyway. The base64 route is probably your best bet still

**Comment by StefanTerdell** [comment]
Added a PR over at Zod for a base64 check. I guess we'll see how that goes :) https://github.com/colinhacks/zod/pull/3047

**Comment by StefanTerdell** [comment]
Hello! A solution to this is now available as of 3.23.0. Since the schema is interpreted to represent the serialized data you can use `z.string().base64()` to represent file contents. By default this results in `"contentEncoding": "base64"` as described [here](https://json-schema.org/understanding-json-schema/reference/non_json_data#contentencoding) but there's also an option (`{ "base64Strategy": "format:binary" }`) to set it to the OpenAPI <=3.0 equivalent

**Comment by StefanTerdell** [comment]
@thelinuxlich

**Comment by thelinuxlich** [comment]
Hey Stefan, this is great! Finally we can represent this type with Zod!
